
=pod

=head1 NAME

gfsmxl_cascade_nbest_lookup - Lookup N-best paths in a gfsmxl cascade



=head1 SYNOPSIS

gfsmxl_cascade_nbest_lookup [OPTIONS] INPUT_WORDS...

 Arguments:
    INPUT_WORDS...  Input strings (implicitly concatenated)

 Options
    -h         --help               Print help and exit.
    -V         --version            Print version and exit.
    -CCASCADE  --cascade=CASCADE    Specify cascade for lookup
    -lLABFILE  --labels=LABFILE     Specify alphabet for string->label lookup
    -pN_PATHS  --max-paths=N_PATHS  Specify maximum number of paths to extract
    -oN_OPS    --max-ops=N_OPS      Specify maximum number of configuration-pop operations
    -wFLOAT    --max-weight=FLOAT   Specify maximum weight of extractable paths
    -a         --att-mode           Respect AT&T regex-style escapes in input strings
    -c         --connect            Connect result prior to output
    -d         --debug              Use old lookup routine (for debugging)
    -FFILE     --output=FILE        Specify output file (default=stdout).

=cut

###############################################################
# Description
###############################################################
=pod

=head1 DESCRIPTION

Lookup N-best paths in a gfsmxl cascade



=cut

###############################################################
# Arguments
###############################################################
=pod

=head1 ARGUMENTS

=over 4

=item C<INPUT_WORDS...>

Input strings (implicitly concatenated)


Required.


=back



=cut


###############################################################
# Options
###############################################################
=pod

=head1 OPTIONS

=over 4

=item C<--help> , C<-h>

Print help and exit.

Default: '0'




=item C<--version> , C<-V>

Print version and exit.

Default: '0'




=item C<--cascade=CASCADE> , C<-CCASCADE>

Specify cascade for lookup

Default: 'cascade.gfsc'


CASCADE should be primarily sorted on lower labels.





=item C<--labels=LABFILE> , C<-lLABFILE>

Specify alphabet for string-E<gt>label lookup

Default: 'cascade.lab'




=item C<--max-paths=N_PATHS> , C<-pN_PATHS>

Specify maximum number of paths to extract

Default: '1'




=item C<--max-ops=N_OPS> , C<-oN_OPS>

Specify maximum number of configuration-pop operations

Default: '-1'




=item C<--max-weight=FLOAT> , C<-wFLOAT>

Specify maximum weight of extractable paths

Default: '1e+38'




=item C<--att-mode> , C<-a>

Respect AT&T regex-style escapes in input strings

Default: '0'




=item C<--connect> , C<-c>

Connect result prior to output

Default: '0'




=item C<--debug> , C<-d>

Use old lookup routine (for debugging)

Default: '0'




=item C<--output=FILE> , C<-FFILE>

Specify output file (default=stdout).

Default: '-'




=back




=cut

###############################################################
# configuration files
###############################################################
=cut



###############################################################
# Addenda
###############################################################
=pod

=head1 ADDENDA



=head2 About this Document

Documentation file auto-generated by optgen.perl version 0.07
using Getopt::Gen version 0.13.
Translation was initiated
as:

   optgen.perl -l --no-handle-rcfile --nocfile --nohfile --notimestamp -F gfsmxl_cascade_nbest_lookup gfsmxl_cascade_nbest_lookup.gog

=cut


###############################################################
# Bugs
###############################################################
=pod

=head1 BUGS AND LIMITATIONS



None known.



=cut

###############################################################
# Footer
###############################################################
=pod

=head1 ACKNOWLEDGEMENTS

Perl by Larry Wall.

Getopt::Gen by Bryan Jurish.

=head1 AUTHOR

Bryan Jurish E<lt>moocow.bovine@gmail.comE<gt>

=head1 SEE ALSO


gfsmutils(1)


=cut


